/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Nat;
export const Scores = IDL.Record({
  'happiness' : IDL.Nat,
  'pollution' : IDL.Nat,
  'forest' : IDL.Nat,
});
export const Decision = IDL.Record({
  'sceneIndex' : IDL.Nat,
  'choiceIndex' : IDL.Nat,
});
export const Session = IDL.Record({
  'scores' : IDL.Opt(Scores),
  'decisions' : IDL.Vec(Decision),
});

export const idlService = IDL.Service({
  'createGameSession' : IDL.Func([], [SessionId], []),
  'getSessionState' : IDL.Func([SessionId], [Session], ['query']),
  'makeDecision' : IDL.Func([SessionId, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Nat;
  const Scores = IDL.Record({
    'happiness' : IDL.Nat,
    'pollution' : IDL.Nat,
    'forest' : IDL.Nat,
  });
  const Decision = IDL.Record({
    'sceneIndex' : IDL.Nat,
    'choiceIndex' : IDL.Nat,
  });
  const Session = IDL.Record({
    'scores' : IDL.Opt(Scores),
    'decisions' : IDL.Vec(Decision),
  });
  
  return IDL.Service({
    'createGameSession' : IDL.Func([], [SessionId], []),
    'getSessionState' : IDL.Func([SessionId], [Session], ['query']),
    'makeDecision' : IDL.Func([SessionId, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };